language: generic
dist: trusty
sudo: required

services:
  - docker

git:
  depth: 1

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      docker build -t fuzzylite -f Dockerfile --build-arg CXX_COMPILER=${CXX_COMPILER} . ;
    fi

script:
##linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      docker run -e CXX=${CXX_COMPILER} -e FL_CPP98=${FL_CPP98} -e FL_USE_FLOAT=${FL_USE_FLOAT} -e FL_BUILD_TESTS=ON -t fuzzylite release ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      docker run -e CXX=${CXX_COMPILER} -e FL_CPP98=${FL_CPP98} -e FL_USE_FLOAT=${FL_USE_FLOAT} -e FL_BUILD_TESTS=ON -t fuzzylite debug ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      docker run -t fuzzylite documentation ;
    fi
##MacOSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      cd fuzzylite/ ;
      ./build.sh release ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      cd fuzzylite/ ;
      ./build.sh debug ;
    fi
matrix:
  include:
############################################################################
# MacOSX
############################################################################
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: CXX_COMPILER=clang FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: CXX_COMPILER=clang FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: CXX_COMPILER=clang FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: CXX_COMPILER=clang FL_CPP98=ON FL_USE_FLOAT=ON
############################################################################
# Latest clang and g++
############################################################################
#clang-4.0
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-4.0 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-4.0 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-4.0 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-4.0 FL_CPP98=ON FL_USE_FLOAT=ON
#g++-7
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-7 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-7 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-7 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-7 FL_CPP98=ON FL_USE_FLOAT=ON
############################################################################
# clang
############################################################################
#clang-3.9
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.9 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.9 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.9 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.9 FL_CPP98=ON FL_USE_FLOAT=ON
#clang-3.8
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.8 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.8 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.8 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.8 FL_CPP98=ON FL_USE_FLOAT=ON
#clang-3.7
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.7 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.7 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.7 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.7 FL_CPP98=ON FL_USE_FLOAT=ON
#clang-3.6
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.6 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.6 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.6 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.6 FL_CPP98=ON FL_USE_FLOAT=ON
#clang-3.5
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.5 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.5 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.5 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: clang
      env: CXX_COMPILER=clang++-3.5 FL_CPP98=ON FL_USE_FLOAT=ON
############################################################################
# g++
############################################################################
#g++-6
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-6 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-6 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-6 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-6 FL_CPP98=ON FL_USE_FLOAT=ON
#g++-5
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-5 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-5 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-5 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-5 FL_CPP98=ON FL_USE_FLOAT=ON
#g++-4.9
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.9 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.9 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.9 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.9 FL_CPP98=ON FL_USE_FLOAT=ON
#g++-4.8
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.8 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.8 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.8 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.8 FL_CPP98=ON FL_USE_FLOAT=ON
#g++-4.7
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.7 FL_CPP98=OFF FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.7 FL_CPP98=OFF FL_USE_FLOAT=ON
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.7 FL_CPP98=ON FL_USE_FLOAT=OFF
    - os: linux
      compiler: g++
      env: CXX_COMPILER=g++-4.7 FL_CPP98=ON FL_USE_FLOAT=ON
############################################################################
# Obsolete compilers
############################################################################
# #clang-3.4 does not install properly in ubuntu (clang++-3.4 command not found)
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.4 FL_CPP98=OFF FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.4 FL_CPP98=OFF FL_USE_FLOAT=ON
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.4 FL_CPP98=ON FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.4 FL_CPP98=ON FL_USE_FLOAT=ON
# #clang-3.3 does not install properly in ubuntu (clang++-3.4 command not found)
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.3 FL_CPP98=OFF FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.3 FL_CPP98=OFF FL_USE_FLOAT=ON
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.3 FL_CPP98=ON FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: clang
#       env: CXX_COMPILER=clang++-3.3 FL_CPP98=ON FL_USE_FLOAT=ON
# #g++-4.6 does not have an installation candidate in ubuntu
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.6 FL_CPP98=OFF FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.6 FL_CPP98=OFF FL_USE_FLOAT=ON
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.6 FL_CPP98=ON FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.6 FL_CPP98=ON FL_USE_FLOAT=ON
# #g++-4.5 does not have an installation candidate in ubuntu
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.5 FL_CPP98=OFF FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.5 FL_CPP98=OFF FL_USE_FLOAT=ON
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.5 FL_CPP98=ON FL_USE_FLOAT=OFF
#     - os: linux
#       compiler: g++
#       env: CXX_COMPILER=g++-4.5 FL_CPP98=ON FL_USE_FLOAT=ON

notifications:
  email:
    recipients:
      - jcrada@fuzzylite.com
    on_success: always
    on_failure: always
